//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class accounting
    {
        public int accountId { get; set; }
        public Nullable<int> accountType { get; set; }
        public Nullable<int> accountUserid { get; set; }
        public Nullable<int> accountRentid { get; set; }
        public Nullable<int> accountMeId { get; set; }
        public Nullable<double> accountMoney { get; set; }
        public Nullable<System.DateTime> accountDate { get; set; }
    
        public virtual Rent Rent { get; set; }
        public virtual MeintanceExamintaion MeintanceExamintaion { get; set; }
        public virtual users users { get; set; }
    }
}
