//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class cars
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cars()
        {
            this.gps = new HashSet<gps>();
            this.Rent = new HashSet<Rent>();
        }
    
        public int carId { get; set; }
        public Nullable<int> carGroup { get; set; }
        public Nullable<int> carKm { get; set; }
        public string carModel { get; set; }
        public string carManufacturer { get; set; }
        public Nullable<int> carCare { get; set; }
        public Nullable<int> carExamination { get; set; }
        public Nullable<double> carPrice { get; set; }
        public Nullable<int> carOK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gps> gps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rent> Rent { get; set; }
    }
}
