//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class gps
    {
        public int gpsId { get; set; }
        public Nullable<double> gpsXcord { get; set; }
        public Nullable<double> gpsYcord { get; set; }
        public Nullable<int> gpsCarId { get; set; }
    
        public virtual cars cars { get; set; }
    }
}
