//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeintanceExamintaion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MeintanceExamintaion()
        {
            this.accounting = new HashSet<accounting>();
        }
    
        public int meId { get; set; }
        public Nullable<System.DateTime> meintanceDate { get; set; }
        public Nullable<System.DateTime> examinationsDate { get; set; }
        public Nullable<int> meCarId { get; set; }
        public Nullable<System.DateTime> meintanceDateNext { get; set; }
        public Nullable<System.DateTime> examinationsDateNext { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<accounting> accounting { get; set; }
    }
}
