//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rent
    {
        

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rent()
        {
            this.accounting = new HashSet<accounting>();
        }
    
        public int rentId { get; set; }
        public Nullable<System.DateTime> rentDate { get; set; }
        public Nullable<System.DateTime> RentFinishDate { get; set; }
        public Nullable<int> carId { get; set; }
        public Nullable<int> userId { get; set; }
        //
        public int carOK { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<accounting> accounting { get; set; }
        public virtual cars cars { get; set; }
        public virtual users users { get; set; }
    }
}
