//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXApplication2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class rentAcarFinalDBEntities : DbContext
    {
        public rentAcarFinalDBEntities()
            : base("name=rentAcarFinalDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<accounting> accounting { get; set; }
        public virtual DbSet<cars> cars { get; set; }
        public virtual DbSet<gps> gps { get; set; }
        public virtual DbSet<groups> groups { get; set; }
        public virtual DbSet<MeintanceExamintaion> MeintanceExamintaion { get; set; }
        public virtual DbSet<MemberShipType> MemberShipType { get; set; }
        public virtual DbSet<Rent> Rent { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
